// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var Message = {};

var ThrowsExpectation = {
  Message: Message
};

var Skip = {};

var ExecutionContext = {
  Skip: Skip
};

var Failing = {};

var Only = {};

var Skip$1 = {};

var Skip$2 = {};

var Always = {
  Skip: Skip$2
};

var Skip$3 = {};

var Assert = {
  Skip: Skip$3
};

exports.ThrowsExpectation = ThrowsExpectation;
exports.ExecutionContext = ExecutionContext;
exports.Failing = Failing;
exports.Only = Only;
exports.Skip = Skip$1;
exports.Always = Always;
exports.Assert = Assert;
/* No side effect */
