// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


let Message = {};

let ThrowsExpectation = {
  Message: Message
};

let Skip = {};

let ExecutionContext = {
  Skip: Skip
};

let Failing = {};

let Only = {};

let Skip$1 = {};

let Skip$2 = {};

let Always = {
  Skip: Skip$2
};

let Skip$3 = {};

let Assert = {
  Skip: Skip$3
};

exports.ThrowsExpectation = ThrowsExpectation;
exports.ExecutionContext = ExecutionContext;
exports.Failing = Failing;
exports.Only = Only;
exports.Skip = Skip$1;
exports.Always = Always;
exports.Assert = Assert;
/* No side effect */
